const { shortId } = require("./ids");

const TEMPLATE_ID = "classic-floral-01";
const TEMPLATE_VERSION = "1.0.0";

function defaultContent() {
  return {
    couple: {
      brideName: "Emma",
      groomName: "James",
    },
    weddingDateTime: {
      date: "2027-06-11",
      startTime: "18:00",
      timezone: "America/New_York",
    },
    text: {
      heroLabel: "Are getting married",
      heroLocation: "Charleston, South Carolina",
      scrollLabel: "Scroll down",
      introHeading: "Together with their families",
      introBody: "We invite you to celebrate with us as we begin this new chapter, surrounded by the people we love most.",
      familyLabel: "Family of",
      saveTheDateHeading: "Save the date",
      saveTheDateBody: "A short wait, then a long celebration.",
      detailsHeading: "The Details",
      detailsBody: "Join us for a day of love and celebration.",
      journeyHeading: "The Journey Up",
      journeyText: "Coaches from the city, then a quiet road to the lake.",
      rsvpHeading: "Kindly Reply",
      rsvpBody: "We hope you can be with us. Please let us know by the date below.",
      scratchPrompt: "Scratch to discover the date",
      scratchCompletionText: "We're getting married!",
      mapsButtonLabel: "View on Maps",
      calendarButtonLabel: "Add to Calendar",
      closingText: "We ask for the pleasure of your company.",
      rsvpNameLabel: "Your name",
      rsvpMessageLabel: "Message (optional)",
      rsvpSubmitLabel: "Send RSVP",
    },
    theme: {
      colors: ["#5a6b5c", "#d4af37", "#8ba3b5"],
    },
    scratch: {
      enabled: true,
      cards: [
        { id: shortId("card"), hiddenText: "SCRATCH", revealText: "11" },
        { id: shortId("card"), hiddenText: "SCRATCH", revealText: "06" },
        { id: shortId("card"), hiddenText: "SCRATCH", revealText: "2027" },
      ],
      completionText: "We're getting married!",
    },
    events: [
      {
        id: shortId("evt"),
        type: "welcome",
        title: "Welcome drinks",
        kicker: "Garden party · citrus and cream",
        venue: "The Willow Garden",
        address: "Charleston, South Carolina",
        date: "2027-06-10",
        startTime: "17:00",
        endTime: "20:00",
        mapsUrl: "https://maps.google.com/?q=The+Willow+Room+Charleston",
        description: "A first toast under the trees.",
        colors: ["#c4a35a", "#7a8b68", "#f7f3ea"],
      },
      {
        id: shortId("evt"),
        type: "ceremony",
        title: "Ceremony",
        kicker: "Soft florals · ivory and sage",
        venue: "The Willow Room",
        address: "Charleston, South Carolina",
        date: "2027-06-11",
        startTime: "16:00",
        endTime: "17:00",
        mapsUrl: "https://maps.google.com/?q=The+Willow+Room+Charleston",
        description: "Please join us as we say our vows.",
        colors: ["#8ba3b5", "#f3ece1", "#3d4f3f"],
      },
      {
        id: shortId("evt"),
        type: "reception",
        title: "Reception",
        kicker: "Black tie optional · ivory and sage",
        venue: "The Willow Room",
        address: "Charleston, South Carolina",
        date: "2027-06-12",
        startTime: "18:00",
        endTime: "23:00",
        mapsUrl: "https://maps.google.com/?q=The+Willow+Room+Charleston",
        description: "Join us for dinner, toasts, and dancing.",
        colors: ["#3d4f3f", "#cbb89a", "#f7f3ea"],
      },
    ],
    location: {
      venue: "The Willow Room",
      address: "Charleston, South Carolina",
      mapsUrl: "https://maps.google.com/?q=The+Willow+Room+Charleston",
    },
    journey: {
      enabled: true,
      title: "The Journey Up",
      subtitle: "Coaches",
      text: "",
      origin: "Central Park, New York",
      destination: "Lake Placid Lodge",
      departLine: "From Central Park, New York · 10 June, 9 AM",
      seatNote: "Tell us and we will keep you a seat",
      meetHeading: "Someone will meet you",
      meetLine: "At the trailhead, and again at the lodge",
      stopNote: "We stop for coffee on the way",
      arrivalHeading: "Once you are here",
      arrivalLine: "Everything is ten minutes from the hotel",
      extraNote: "Boats on the lake from morning",
      mapsUrl: "https://maps.google.com/?q=Lake+Placid+Lodge+New+York",
      imageUrl: "",
    },
    media: {
      heroImageUrl: "/assets/hero-archway.jpg",
      gallery: [],
      musicUrl: "/assets/sample-music.mp3",
    },
    rsvp: {
      enabled: true,
      deadline: "2027-05-20",
      attendanceOptions: ["yes", "no"],
    },
    language: "en",
  };
}

module.exports = { TEMPLATE_ID, TEMPLATE_VERSION, defaultContent };
